### ISSUE TITLE
how to add class to captcha field?

### ISSUE THREAD

**Issue by vaibhavmule** [alsoicode/django-simple-math-captcha#14]
```
captcha = MathCaptchaField(label="Solve the equation: \a")
```

This is what I want to achieve, I want to add `form-control` class to this field.
```
captcha = MathCaptchaField(label="Solve the equation: \a", class="form-control")
```
cc: @mottled

**Comment by alsoicode** [comment]
Hi. The captcha itself is really just a span tag that gets included next to Django's built in multiwidget:

```
<span class="{{ question_class }}">{{ question_html }}</span>{% include 'django/forms/widgets/multiwidget.html' %}
```

To get the Bootstrap classing you're needing, you're best off just rendering the form by hand and wrapping the entire field with the `form-control` class where you need it for your layout rather than trying to add it programmatically.

**Comment by vaibhavmule** [comment]
I know this is not suggested but for now, things are working as I have made changes in the package itself which were in the virtual environment. This I felt is really quick. 

https://github.com/alsoicode/django-simple-math-captcha/blob/master/simplemathcaptcha/widgets.py#L21

just changed that line to this,

```
widget_attrs = {'size': '5', 'class': 'form-control'}
```

**Comment by alsoicode** [comment]
You'll have to forgive me as it's been a while since I've worked with this package, but if memory serves, you should be able to do:

```
MathCaptchaField(label="Solve the equation: \a", attrs={'class': 'form-control'})
```
